### ISSUE TITLE
impossible to install via pip

### ISSUE THREAD

**Issue by pahenator** [pygobject/pgi#54]
pip install pgi      
Collecting pgi
  Using cached pgi-0.0.11.2.tar.gz (239 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\setup.py", line 18, in <module>
          import pgi
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\pgi\__init__.py", line 10, in <module>
          from .importer import require_version, get_required_version
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\pgi\importer.py", line 15, in <module>
          from .clib.gir import GIRepository
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\pgi\clib\gir\__init__.py", line 8, in <module>  
          from .giargument import GIArgument
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\pgi\clib\gir\giargument.py", line 9, in <module>          from ..glib import gboolean, gint8, guint8, gint16, guint16, gint32, guint32
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\pgi\clib\glib.py", line 16, in <module>
          _glib = find_library("glib-2.0")
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pavel\AppData\Local\Temp\pip-install-_znv085p\pgi_92ca1d9f5e694cb7bb3831f3de8c8dbb\pgi\clib\_utils.py", line 99, in find_library   
          _internal[name] = cdll.LoadLibrary(_so_mapping[name])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pavel\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 454, in LoadLibrary
          return self._dlltype(name)
                 ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pavel\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
          self._handle = _dlopen(self._name, mode)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: Could not find module 'libglib-2.0-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by pahenator** [comment]
libglib-2.0-0.dll
I added this lib to System32 but still no luck

**Comment by hmLin2002** [comment]
I encounter the same problem. Could you tell me how to solve it? Thank you!

**Comment by TingPing** [comment]
You'd have to get the libraries through another method, such as [msys2](https://www.msys2.org/) or [wingtk](https://github.com/wingtk/gvsbuild)

**Comment by pahenator** [comment]
> You'd have to get the libraries through another method, such as [msys2](https://www.msys2.org/) (mingw) or [wingtk](https://github.com/wingtk/gvsbuild) (msvc)

it was long time ago, as I remember I didn't solve this issue. Try clear install from scratch on VM with clan Windows installation
